#!/usr/bin/env bash

# TILING MANAGER

# change window focus within space
alt - j : yabai -m window --focus south
alt - k : yabai -m window --focus north
alt - h : yabai -m window --focus west
alt - l : yabai -m window --focus east

# change focus between external displays (left and right)
alt - s: yabai -m display --focus west
alt - g: yabai -m display --focus east

# rotate layout clockwise
# shift + alt - r : yabai -m space --rotate 270

# flip along y-axis / x-axis
shift + alt - y : yabai -m space --mirror y-axis
shift + alt - x : yabai -m space --mirror x-axis

# toggle window float
alt - t : yabai -m window --toggle float --grid 4:4:1:1:2:2

# toggle window fullscreen
alt - f : yabai -m window --toggle zoom-fullscreen
shift + alt - f : yabai -m window --toggle native-fullscreen

# balance out tree of windows (resize to occupy same area)
shift + alt - e : yabai -m space --balance


# swap windows
shift + alt - j : yabai -m window --swap south
shift + alt - k : yabai -m window --swap north
shift + alt - h : yabai -m window --swap west
shift + alt - l : yabai -m window --swap east

# resize windows
ctrl + alt - h : yabai -m window --resize right:-30:0 || yabai -m window --resize left:-30:0
ctrl + alt - j : yabai -m window --resize bottom:0:30 || yabai -m window --resize top:0:30
ctrl + alt - k : yabai -m window --resize bottom:0:-30 || yabai -m window --resize top:0:-30
ctrl + alt - l : yabai -m window --resize right:30:0 || yabai -m window --resize left:30:0

# move window and split
ctrl + alt - j : yabai -m window --warp south
ctrl + alt - k : yabai -m window --warp north
ctrl + alt - h : yabai -m window --warp west
ctrl + alt - l : yabai -m window --warp east

# move window to display left and right
# shift + alt - s : yabai -m window --display west; yabai -m display --focus west;
# shift + alt - g : yabai -m window --display east; yabai -m display --focus east;

# move window to prev and next space
shift + alt - p : yabai -m window --space prev;
shift + alt - n : yabai -m window --space next;

# move window to space #
shift + alt - 1 : yabai -m window --space 1;
shift + alt - 2 : yabai -m window --space 2;
shift + alt - 3 : yabai -m window --space 3;
shift + alt - 4 : yabai -m window --space 4;
shift + alt - 5 : yabai -m window --space 5;
shift + alt - 6 : yabai -m window --space 6;
shift + alt - 7 : yabai -m window --space 7;

# move focus to space #
alt - 1 : yabai -m space --focus 1; [ -z "$(yabai -m query --windows --window)" ] && yabai -m window --focus first
alt - 2 : yabai -m space --focus 2; [ -z "$(yabai -m query --windows --window)" ] && yabai -m window --focus first
alt - 3 : yabai -m space --focus 3; [ -z "$(yabai -m query --windows --window)" ] && yabai -m window --focus first
alt - 4 : yabai -m space --focus 4; [ -z "$(yabai -m query --windows --window)" ] && yabai -m window --focus first
alt - 5 : yabai -m space --focus 5; [ -z "$(yabai -m query --windows --window)" ] && yabai -m window --focus first
alt - 6 : yabai -m space --focus 6; [ -z "$(yabai -m query --windows --window)" ] && yabai -m window --focus first
alt - 7 : yabai -m space --focus 7; [ -z "$(yabai -m query --windows --window)" ] && yabai -m window --focus first

### on changing spaces, focus on first window in space if no windows are previously focused

# stop/start/restart yabai
shift + alt - escape : yabai --stop-service && pkill yabai
# shift + alt - escape : pkill yabai
shift + alt - r : yabai --start-service && yabai --restart-service
shift + alt - o : brew services start yabai


# APP LAUNCHER

# ctrl + shift - return : yabai -m signal --add label=float_next_application_launched event=application_launched action='yabai -m window --toggle float --grid 4:4:1:1:2:2'; wezterm

alt + shift - m : nohup ~/.config/home-manager/scripts/rofi-beats > /dev/null 2>&1 &

# open terminal, blazingly fast compared to iTerm/Hyper
alt - return : /Applications/kitty.app/Contents/MacOS/kitty --single-instance -d ~

alt + shift - return : wezterm --single-instance -d ~

# alt - e: cd ~/.config/home-manager && ls | choose | xargs -I {} zed "{}"

# alt - e : cd ~/.config/home-manager && ls | choose | xargs -I {} wezterm start --cwd ~/.config/home-manager -- hx "{}"

alt - e : dir="$HOME/.config/home-manager"; while true; do item=$(cd "$dir" && ls | choose); [ -z "$item" ] && break; if [ -d "$dir/$item" ]; then dir="$dir/$item"; else wezterm start --cwd "$dir" -- hx "$item"; break; fi; done


# alt - e : dir="$HOME/.config/home-manager"; while true; do item=$(cd "$dir" && ls | choose); if [ -d "$dir/$item" ]; then dir="$dir/$item"; else wezterm start --cwd "$dir" -- hx "$item"; break; fi; done
