#!/usr/bin/env bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# --- TILING

### --- LAYOUT

# bsp or float (default: float)
yabai -m config layout bsp

# ovveride layout for space 5 only
yabai -m config --space 5 layout float

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

### --- PADDING / GAPS

# Set all padding and gaps to 12pt (default: 0)
yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 12

# Override gaps for space 5 only
yabai -m config --space 5 window_gap 0

### --- SPLIT RATIOS

yabai -m config auto_balance on

# Floating point value between 0 and 1 (default: 0.5)
# yabai -m config split_ratio 0.3

### --- MOUSE SUPPORT

# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m mouse_drop_action swap

# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt

# set modifier + left-click drag to move window
yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
yabai -m config focus_follows_mouse autoraise

# set mouse follows focus mode (default: off)
yabai -m config mouse_follows_focus on

# --- WINDOW MODIFICATIONS

# modify window shadows (default: on, options: on, off, float)
# example: show shadows only for floating windows
yabai -m config window_shadow float

# window opacity (default: off)
# example: render all unfocused windows with 90% opacity
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9

# --- STATUS BAR

# add 20 padding to the top and 0 padding to the bottom of every space located on the main display
yabai -m config external_bar main:20:0

# add 20 padding to the top and bottom of all spaces regardless of the display it belongs to
yabai -m config external_bar all:32:20


# --- OTHER

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off

yabai -m rule --add title="ddterm" manage=off grid="10:1:0:0:1:4"

yabai -m signal --add event=window_created \
    app="WezTerm" \
    action="yabai -m window --focus \$YABAI_WINDOW_ID"


# JankyBorders
# borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 &

options=(
	# style=round
	# width=6.0
	# hidpi=off
	# active_color=0xc0e2e2e3
	inactive_color=0xff494d64
	# inactive_color=0xc02c2e34
	# background_color=0x302c2e34
)

borders "${options[@]}"

# borders style=round width=6.0 active_color=0xffe1e3e4 inactive_color=0xff494d64&


