{
  lib,
  pkgs,
  path,
  ...
}:

let
  inherit (path)
    dot
    home
    hm
    nix
    ;

  shellAliases = import ./alias.nix;
  # python-packages = import ./python.nix;
in
# user packages, not available in sudo mode
{
  launchd.agents.glance = {
    enable = true;
    config = {
      Label = "dev.glance";
      ProgramArguments = [
        "/bin/zsh"
        "-lc"
        ''
          set -euo pipefail

          # load secrets generated by your zsh.nix activation step
          source "$HOME/.cache/zsh/secrets.env"

          exec '${pkgs.glance}/bin/glance' -config '${dot}/glance/glance.yml'
        ''
      ];
      RunAtLoad = true; # start at login
      KeepAlive = true; # restart if it exits
      WorkingDirectory = hm;
      StandardOutPath = "${home}/Library/Logs/glance/glance.out.log";
      StandardErrorPath = "${home}/Library/Logs/glance/glance.err.log";
    };
  };
  home = {
    homeDirectory = home;
    stateVersion = "26.05";

    sessionPath =
      (map (f: "$HOME/${f}") [
        ".cargo/bin"
        ".local/bin"
        ".bun/bin"
        ".nix-profile/bin"
        "go/bin"
        ".rustup/toolchains/esp/xtensa-esp-elf/esp-15.2.0_20250920/xtensa-esp-elf/bin"
      ])
      ++ [
        "/opt/homebrew/bin"
        "/run/current-system/sw/bin"
        "/nix/var/nix/profiles/default/bin"
        "/etc/profiles/per-user/$USER/bin"
      ];

    sessionVariables = {
      NX = nix;
      HM = hm;
      DW = path.darwin;
      DOT = dot;
      SCRIPTS = path.scripts;
      SNIPPETS_PATH = path.snippets; # for scls
      SHARE = path.share;

      EDITOR = "hx";
      CODEX_HOME = "${dot}/codex";
      SOPS_AGE_KEY_FILE = "${nix}/secrets/keys.txt"; # sops key location
      LIBCLANG_PATH = "${home}/.rustup/toolchains/esp/xtensa-esp32-elf-clang/esp-20.1.1_20250829/esp-clang/lib";
    };

    shell.enableZshIntegration = true;
    shell.enableFishIntegration = true;
    shellAliases = shellAliases;

    file =
      lib.mapAttrs (_: path.mkDotFile) {
        ".config/aerospace" = "aerospace";
        ".config/glance/glance.yml" = "glance/glance.yml";
        # ".codex/prompts" = "codex/prompts";
        # ".codex/AGENTS.md" = "codex/AGENTS.md";
        ".config/rio" = "rio";
        ".config/rmpc" = "rmpc";
        ".config/sketchybar" = "sketchybar";
        ".config/zellij" = "zellij";
        ".config/zk" = "zk";
        ".config/zsh/.p10k.zsh" = "p10k/.p10k.zsh";
        ".mpd/mpd.conf" = "mpd/mpd.conf";
        "Library/Application Support/com.mitchellh.ghostty" = "ghostty";
        # ".config/nushell".source = ~/dotfiles/nushell;
      }
      // {
        # ensure launchd log directory exists so glance can start at login
        "Library/Logs/glance/.keep".text = "";
      };

    packages =
      with pkgs;
      [
        # (python314.withPackages python-packages)

        curlie # curl
        procs # ps
        sd # sed
        mprocs
        nix-converter

        freeze # generate images of code/terminal out
        dua # disk util of dir (extra? yazi space usage?)
        kondo # clean deps and build artifacts from proj
        clipboard-jh

        toolong # log files

        # esp
        espflash

        # JSON
        jnv
        gojq
        fx
        jless
        jqp

        # # helix lsps
        nixd # Nix
        nixfmt # nix official

        circumflex # browse hacker news
        ticker # cli stock ticker
        zk # note-taking assistant
        typst
        google-cloud-sdk
        restic # efficient & secure backup
        duckdb # embeddable analytics db

        coreutils-full # gnu core utils
        bagels # tui expense tracker
        # gurk-rs # signal messenger terminal client; causes nix error...
        sc-im # spreadsheet calculator

        dysk # disk usage
        memos # memo hub
        # texliveFull # comprehensive latex system, pdf engine
        glance # self-hosted browser dashboard
        mas # mac app store cli
        sqlfluff
        tigerbeetle # high performance transactional db

        dprint

        # Rust Dev
        rustup
        cargo-watch
        cargo-make
        dioxus-cli
        cargo-binstall

        # RSS
        nom

        # RS tools
        hyperfine # cli benchmarking tool
        tokei # count lines of code
        rsync # backup & two-way sync

        age # encryption tool
        sops # manage secrets
        # crush
        ripgrep
        glow # preview md
        gum # shell script ui
        entr # run command on file change
        nb # cli local note-taking
        # jrnl # collect thoughts and notes in terminal
        mods # cli llm
        # aichat # cli api llm
        # open-webui # ui for local AI models
        tldr # community man
        cht-sh # cli for cheat.sh (comprehensive cheatsheets)
        # tlrc # tldr client in rust
        presenterm # md cli slideshow
        macmon # apple silicon performance monitoring
        gping # ping with a graph
        github-mcp-server

        dnscrypt-proxy
        openapi-tui
        sshs

        # GO
        envsubst
        sttr # text transformation

        # rustic # deduplicated and encrypted backup, takes folder snapshots

        # MEDIA (audio / video)
        ffmpeg # cli edit/convert/stream multimedia content
        # termscp # file transfer; error?
        kew # music player

        # Task Tracking

        # Jujutsu
        jjui
        lazyjj

        # GIT
        glab # gitlab cli
        tig

        # docker
        dive # explore layer in docker image
        ctop # top-like interface for containers

        # dev tools
        zig
        dep-tree # visualize complexities of a codebase
        protobuf_32
        act # run github actions locally
        kubernetes-helm # package manager for kubernetes
        minikube
        # ollama
        # uv # pip replacement (in rust)
        litecli # for sqlite
        # pgcli # for postgres
        clang-tools
        lldb_19
        nettools
        just # project-level command runner
        # icu76 # unicode/globalization
        lefthook # git hooks manager (like husky)
        gitleaks # check for secrets
        # claude-code # agentic coding tool in terminal
        cloudflared
        # n8n
        jql # query json from cli
        yq-go # YAML, TOML, JSON and XML processor
        dasel # select/put/delete data from files
        hexyl # hex viewer
        serpl # global search and replace
        dust # faster du
        duf # better df
        # calcure # tui calendar + task manager
        silicon # Create beautiful image of your source code
        asciinema_3 # record terminal session
        vhs # generate gifs with code
        k6 # load testing

        # db
        sqlite
        postgresql
        sqlc
        turso-cli

        # other
        mdbook # create book from md files
        mdbook-linkcheck # check links
        ttyper # terminal typing test
        lychee # broken links checker
        puffin # personal finance dashboard

        # visuals
        chafa
        onefetch # git repo
        fastfetch
        cbonsai
        rust-stakeholder # troll: impressive-looking nonsense terminal output
        # macchina
        # asciiquarium-transparent
        # cowsay
        # ponysay
        # fortune
        # lolcat
        ### combo (ie fortune | ponysay | lolcat)

        # elixir_1_18
        go
        go-swag # API docs
        delve # go debugger
        air # live reload for go
        pkgsite # generate docs for go
        errcheck # checks unchecked erros in go

        sqlc # generate type-safe code from SQL
        goose # db migration tool

        ghc
        ghcid
        stack # stack has own version of ghc?
        haskell-language-server
        hlint

        haskellPackages.cabal-install
      ]
      ++ lib.optionals stdenv.isDarwin [
        # for mac-specific packages
        m-cli # useful macOS CLI commands
      ];
  };
}
