{ path, pkgs, ... }:

let
  inherit (path)
    dot
    home
    hm
    ;
in
{
  launchd.agents.glance = {
    enable = true;
    config = {
      Label = "dev.glance";
      ProgramArguments = [
        "/bin/zsh"
        "-lc"
        ''
          set -euo pipefail

          # load secrets generated by your zsh.nix activation step
          source "$HOME/.cache/zsh/secrets.env"

          exec '${pkgs.glance}/bin/glance' -config '${dot}/glance/glance.yml'
        ''
      ];
      RunAtLoad = true; # start at login
      KeepAlive = true; # restart if it exits
      WorkingDirectory = hm;
      StandardOutPath = "${home}/Library/Logs/glance/glance.out.log";
      StandardErrorPath = "${home}/Library/Logs/glance/glance.err.log";
    };
  };

  # support eilmeldung, rss feed
  launchd.agents.miniflux = {
    enable = true;
    config = {
      Label = "eilmeldung.miniflux";
      ProgramArguments = [
        "/bin/zsh"
        "-lc"
        ''
          exec '${pkgs.miniflux}/bin/miniflux' -config '${dot}/miniflux/config.env'
        ''
      ];
      RunAtLoad = true; # start at login
      KeepAlive = true; # restart if it exits
      WorkingDirectory = hm;
      StandardOutPath = "${home}/Library/Logs/miniflux/miniflux.out.log";
      StandardErrorPath = "${home}/Library/Logs/miniflux/miniflux.err.log";
    };
  };

  home.packages = with pkgs; [
    ## knowledge tools
    memos # memo hub
    zk # note-taking assistant
    nb # cli local note-taking
    bmm # cli bookmark manager
    # texliveFull # comprehensive latex system, pdf engine
    glance # self-hosted browser dashboard
    # jrnl # collect thoughts and notes in terminal
    miniflux # rss backend
    todoist

    circumflex # browse hacker news
  ];
}
