{ path, pkgs, ... }:

let
  inherit (path)
    dot
    home
    hm
    ;

  pg = pkgs.postgresql_18;
  pgRoot = "${home}/Library/Application Support/Postgres/18";
  pgData = "${pgRoot}/data";
  pgSocket = "${pgRoot}/socket";
in
{
  launchd.agents = {
    glance = {
      enable = true;
      config = {
        Label = "dev.glance";
        ProgramArguments = [
          "/bin/zsh"
          "-lc"
          ''
            set -euo pipefail

            # load secrets generated by your zsh.nix activation step
            source "$HOME/.cache/zsh/secrets.env"

            exec '${pkgs.glance}/bin/glance' -config '${dot}/glance/glance.yml'
          ''
        ];
        RunAtLoad = true; # start at login
        KeepAlive = true; # restart if it exits
        WorkingDirectory = hm;
        StandardOutPath = "${home}/Library/Logs/glance/glance.out.log";
        StandardErrorPath = "${home}/Library/Logs/glance/glance.err.log";
      };
    };

    # postgres18 = {
    #   enable = true;
    #   config = {
    #     Label = "dev.postgres18";
    #     ProgramArguments = [
    #       "/bin/zsh"
    #       "-lc"
    #       ''
    #         set -euo pipefail
    #         mkdir -p '${pgData}' '${pgSocket}' "${home}/Library/Logs/postgres18"

    #         # Initialize once
    #         if [ ! -f '${pgData}/PG_VERSION' ]; then
    #           exec '${pg}/bin/initdb' -D '${pgData}' --encoding=UTF8 --locale=C
    #         fi

    #         # Run server (unix socket in pgSocket, port 5432)
    #         exec '${pg}/bin/postgres' -D '${pgData}' -k '${pgSocket}' -p 5432
    #       ''
    #     ];
    #     RunAtLoad = true;
    #     KeepAlive = true;
    #     StandardOutPath = "${home}/Library/Logs/postgres18/postgres.out.log";
    #     StandardErrorPath = "${home}/Library/Logs/postgres18/postgres.err.log";
    #   };
    # };

    # support eilmeldung, rss feed
    miniflux = {
      enable = true;
      config = {
        Label = "eilmeldung.miniflux";
        ProgramArguments = [
          "/bin/zsh"
          "-lc"
          ''
            until '${pkgs.postgresql_18}/bin/pg_isready' -h 127.0.0.1 -p 5432 >/dev/null 2>&1; do
              sleep 1
            done

            exec '${pkgs.miniflux}/bin/miniflux' -config '${dot}/miniflux/config.env'
          ''
        ];
        RunAtLoad = true; # start at login
        KeepAlive = true; # restart if it exits
        WorkingDirectory = hm;
        StandardOutPath = "${home}/Library/Logs/miniflux/miniflux.out.log";
        StandardErrorPath = "${home}/Library/Logs/miniflux/miniflux.err.log";
      };
    };
  };

  home.packages = with pkgs; [
    ## knowledge tools
    memos # memo hub
    zk # note-taking assistant
    nb # cli local note-taking
    bmm # cli bookmark manager
    # texliveFull # comprehensive latex system, pdf engine
    glance # self-hosted browser dashboard
    # jrnl # collect thoughts and notes in terminal
    miniflux # rss backend
    todoist

    circumflex # browse hacker news

    # (rustPlatform.buildRustPackage {
    #   pname = "ck";

    #   # Version is up to you; you can derive from the git rev if you want
    #   version = "git-${zesh-src.rev or "dev"}";

    #   # Use the source from the flake input
    #   src = inputs.ck;

    #   # Re-use the lockfile from the repo
    #   cargoLock.lockFile = "${zesh-src}/Cargo.lock";

    #   meta = with pkgs.lib; {
    #     description = "ck for semantic search in cli";
    #     homepage = "https://github.com/BeaconBay/ck";
    #     license = licenses.mit;
    #     platforms = platforms.darwin;
    #   };
    # })
  ];
}
