{
  lib,
  path,
  pkgs,
  ghostty,
  ...
}:

let
  shellAliases = import ./alias.nix;
in
# user packages, not available in sudo mode
{
  # launchd.agents.glance = {
  #   enable = true;
  #   config = {
  #     Label = "dev.glance";
  #     ProgramArguments = [
  #       "/bin/zsh"
  #       "-lc"
  #       ''
  #         set -euo pipefail

  #         # load secrets generated by your zsh.nix activation step
  #         source "$HOME/.cache/zsh/secrets.env"

  #         exec '${pkgs.glance}/bin/glance' -config '${dot}/glance/glance.yml'
  #       ''
  #     ];
  #     RunAtLoad = true; # start at login
  #     KeepAlive = true; # restart if it exits
  #     WorkingDirectory = hm;
  #     StandardOutPath = "${home}/Library/Logs/glance/glance.out.log";
  #     StandardErrorPath = "${home}/Library/Logs/glance/glance.err.log";
  #   };
  # };

  programs.home-manager = {
    enable = true;
  };
  home = {
    # homeDirectory = home;
    username = "davinci";
    homeDirectory = "/home/davinci";
    stateVersion = "26.05";

    sessionPath = (
      map (f: "$HOME/${f}") [
        ".cargo/bin"
        ".local/bin"
        ".bun/bin"
        ".nix-profile/bin"
        "go/bin"
      ]
    );

    sessionVariables = {
      NX = path.nix;
      MOD = path.mod;
      DOT = path.dot;
      SCRIPTS = path.scripts;
      SNIPPETS_PATH = path.snippets; # for scls
      SHARE = path.share;

      EDITOR = "hx";
      #   CODEX_HOME = "${dot}/codex";
      #   SOPS_AGE_KEY_FILE = "${nix}/secrets/keys.txt"; # sops key location
      #   LIBCLANG_PATH = "${home}/.rustup/toolchains/esp/xtensa-esp32-elf-clang/esp-20.1.1_20250829/esp-clang/lib";
    };

    shell = {
      enableZshIntegration = true;
      enableFishIntegration = true;
    };
    shellAliases = shellAliases;

    file =
      lib.mapAttrs (_: path.mkDotFile) {
        # ".config/keyd/app.conf" = "keyd/app.conf";
        # ".config/glance/glance.yml" = "glance/glance.yml";
        #     # ".codex/prompts" = "codex/prompts";
        #     # ".codex/AGENTS.md" = "codex/AGENTS.md";
        #     ".config/rio" = "rio";
        #     ".config/rmpc" = "rmpc";
        #     ".config/sketchybar" = "sketchybar";
        #     ".config/zellij" = "zellij";
        #     ".config/zk" = "zk";
        #     ".config/zsh/.p10k.zsh" = "p10k/.p10k.zsh";
        #     ".mpd/mpd.conf" = "mpd/mpd.conf";
        #     "Library/Application Support/com.mitchellh.ghostty" = "ghostty";
        #     # ".config/nushell".source = ~/dotfiles/nushell;
      }
      // {
        # "/etc/keyd/default.conf" = "~/f0nix/modules/dotfiles/keyd/default.conf";
        # ensure launchd log directory exists so glance can start at login
        # "Library/Logs/glance/.keep".text = "";
      };

    packages =
      with pkgs;
      [
        glibc

        # helix lsps
        nixd # Nix
        nixfmt # nix official

        typst

        # db
        duckdb # embeddable analytics db
        tigerbeetle # high performance transactional db

        # Zig Dev
        zig

        # Rust Dev
        rustup
        cargo-watch
        cargo-make
        dioxus-cli
        cargo-binstall

        # cli tools
        ripgrep
        serpl # global search and replace
        dust # faster du
        duf # better df
        dysk # disk usage
        curlie # curl
        procs # ps
        sd # sed
        toolong # log files
        kondo # clean deps and build artifacts from proj
        nix-converter

        # RS tools
        hyperfine # cli benchmarking tool
        tokei # count lines of code

        # Encryption
        age # encryption tool
        sops # manage secrets

        # MEDIA (audio / video)
        ffmpeg # cli edit/convert/stream multimedia content

        # Jujutsu
        jjui
        lazyjj

        # dev tools
        dprint
        just # project-level command runner
        lefthook # git hooks manager (like husky)
      ]
      ++ lib.optionals stdenv.isLinux [
        ghostty.packages.${pkgs.stdenv.hostPlatform.system}.default
      ]
      ++ lib.optionals stdenv.isDarwin [
        m-cli # useful macOS CLI commands
      ];

  };
}
